org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties (see https://fabricmc.net/develop)
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.161.0+26.3
geckolib_version=5.5.7
jmdns_version=3.6.3

# Mod Properties
mod_version=0.1.0
maven_group=dev.michidk.voxvelo
archives_base_name=voxvelo
