// Writes the licence texts of every Rust crate compiled into the Bluetooth library, for all shipped platforms, to
// src/fitness/main/resources/META-INF/licenses/voxvelo_ble-THIRD-PARTY.txt. Run after changing dependencies:
//   node native/ble/licenses.mjs
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const output = join(here, '../../src/fitness/main/resources/META-INF/licenses/voxvelo_ble-THIRD-PARTY.txt');
const targets = [
	'x86_64-pc-windows-msvc',
	'aarch64-pc-windows-msvc',
	'x86_64-unknown-linux-gnu',
	'aarch64-unknown-linux-gnu',
	'x86_64-apple-darwin',
	'aarch64-apple-darwin',
];

const cargo = (...args) => execFileSync('cargo', args, { cwd: here, encoding: 'utf8', maxBuffer: 64 << 20 });

// Crates linked into the library on any target: normal dependencies only, so build scripts and macros are left out.
const shipped = new Set();
for (const target of targets) {
	const tree = cargo('tree', '--target', target, '-e', 'normal,no-proc-macro', '--prefix', 'none', '-f', '{p}');
	for (const line of tree.split('\n')) {
		const [name, version] = line.trim().split(' ');
		if (name && version && name !== 'voxvelo_ble') shipped.add(`${name} ${version.replace(/^v/, '')}`);
	}
}

const metadata = JSON.parse(cargo('metadata', '--format-version', '1', '--locked'));
const packages = metadata.packages
	.filter(p => shipped.has(`${p.name} ${p.version}`))
	.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const seen = new Map();
const sections = [];
for (const p of packages) {
	const root = dirname(p.manifest_path);
	const files = readdirSync(root).filter(f => /^(licen[cs]e|copying|notice|copyright)/i.test(f)).sort();
	let section = `${p.name} ${p.version}\nLicence: ${p.license ?? p.license_file ?? 'see below'}\n`;
	if (p.repository) section += `Source: ${p.repository}\n`;
	if (files.length === 0) section += '\n(No licence file in the published crate; see the licence named above.)\n';
	for (const file of files) {
		const text = readFileSync(join(root, file), 'utf8').replace(/\r\n/g, '\n').trimEnd();
		const hash = createHash('sha256').update(text).digest('hex');
		if (seen.has(hash)) {
			section += `\n${file}: identical to ${seen.get(hash)}\n`;
		} else {
			seen.set(hash, `${file} of ${p.name} ${p.version}`);
			section += `\n----- ${file} -----\n${text}\n`;
		}
	}
	sections.push(section);
}

const header = `Third-party licences of the VoxVelo Bluetooth library (voxvelo_ble, bundled in natives/)

The library is built from native/ble in the VoxVelo repository (MIT) and statically links the Rust crates below.
Generated by native/ble/licenses.mjs from the crates' own licence files.
`;
writeFileSync(output, [header, ...sections].join('\n' + '='.repeat(100) + '\n\n'));
console.log(`${packages.length} crates -> ${output}`);
